### ISSUE TITLE
Execute with bash. Exit.

### ISSUE THREAD

**Issue by alberttra** [realvnc-labs/rport#1060]
I try to run the installer for the first time on hetzner ubuntu and got `Execute with bash. Exit.` and nothing else. Does anyone known what is problem?

**Comment by thorstenkramm** [comment]
@alberttra 
You tried to execute with `sh` or some other shell. Use `bash`. The installer requires some features not provided by `sh` but provided by `bash`. 

```bash
curl https://get.rport.io -o rport-install.sh
bash rport-install.sh
```
[Read more](https://kb.rport.io/install-the-rport-server/install-rport-on-any-virgin-cloud-vm)

**Comment by alberttra** [comment]
that is the problem that i am facing ^^ I did run it with `bash`. The `which bash` return `/bin/bash` and I did use the command `bash rport-install.sh`

![image](https://github.com/realvnc-labs/rport/assets/16648814/abfda7f8-98ff-4364-81cc-2c73020da91a)

**Comment by thorstenkramm** [comment]
@alberttra From the screenshot I can see you have "tweaked" your shell because having the execution time displayed is not the default.
What does your environment variable `$SHELL` resolve to?
And what do you get, if you execute `bash -c "echo $SHELL"`?

If you are sure, you are on a bash shell, just open the installer script and delete these lines somewhere at the beginning of the file:
```
if [[ $SHELL =~ bash ]] 2>/dev/null;then
    true
else
    2>&1 echo "Execute with bash. Exit."
    exit 1
fi
```

**Comment by alberttra** [comment]
> If you are sure, you are on a bash shell, just open the installer script and delete these lines somewhere at the beginning of the file:
> 
> ```
> if [[ $SHELL =~ bash ]] 2>/dev/null;then
>     true
> else
>     2>&1 echo "Execute with bash. Exit."
>     exit 1
> fi
> ```

That helped 👍 Thx
