### ISSUE TITLE
Schedule button only becomes clickable when selecting machines from "individual_clients" tab.

### ISSUE THREAD

**Issue by d3al** [realvnc-labs/rport#1067]
**Describe the bug**
While on the script screen and wanting to create a schedule for various groups of machines. Only way the schedule button becomes clickable is by selecting individual machines on the "individual_clients" tab. Other three tabs don't enable the schedule button.

**Environment**
Describe the environment where the bug occurs:

* RPort version: 9.12

**Comment by thorstenkramm** [comment]
@d3al 
We have partially fixed it.
The button now becomes available for all client targeting options except for tags because the current backend doesn't support schedules based on tags. The next version of rport server will support it.

Try updating the frontend to the latest version [frontend 0.9.12-5](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by d3al** [comment]
Confirmed the schedule button is clickable upon selecting machines/groups from various tabs.

Thank you.
