### ISSUE TITLE
Azure VM  setup guide from Website not working as expected

### ISSUE THREAD

**Issue by LoopedSdrawkcaB** [realvnc-labs/rport#1084]
- Azure VM
- Debain 11 / Standard B1s

I'm currently in the process of setting up an Azure VM. I have successfully configured a Fully Qualified Domain Name (FQDN) and set up a DNS record that directs to the IP address of the Azure VM. I have confirmed that the domain name resolves correctly, and I am able to establish an SSH connection to the machine. Additionally, I have followed the provided guide to forward all necessary ports.

However, I'm encountering difficulties when attempting to connect to the machine using either the FQDN or the IP address. When I try to generate a certificate with Certbot, I encounter the error message: 'Timeout during connect (likely firewall problem).' I have double-checked that the timezone is correctly set on the Debian machine, and I can confirm that there are no firewalls installed.

Moreover, I've attempted to set outbound port rules for port 80 and 443 without success. I also ran the troubleshooter within the Azure VM, which indicates that there is connectivity. However, when I search the IP on a port checker, port 80 still appears to be blocked.

If anyone has any ideas or suggestions, I would greatly appreciate the assistance
![Capture](https://github.com/realvnc-labs/rport/assets/63082440/85ac8a4d-0088-4c9c-9c50-7f43b4275f27)

**Comment by thorstenkramm** [comment]
@LoopedSdrawkcaB 
You are using the latest version of the rport server which comes with the [ACME built-in](https://oss.rport.io/get-started/securing-rportd-with-https/#use-the-built-in-acme). You don't need certbot.
Please check the log file `/var/log/rport/rportd.log`. 

If the rport server is running you cannot use certbot because rport is using the ports 80 and 443. If you want to generate the certs with Certbot, you must stop `rportd` during the execution of Certbot. But you shouldn't do that. Let the rport server do it. 

> Moreover, I've attempted to set outbound port rules for port 80 and 443 without success.

You need **inbound** rules. AFAIK Azure doesn't have any outbound rules by default. All outbound connections are allowed. Check your inbound rules. [This article](https://kb.rport.io/install-the-rport-server/install-on-azure) might help.

Also check your `/etc/rport/rpportd.conf` file. Which values have been set for `base_url` and for `enable_acme`?
